name: flutter_monisite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.4
  dio: ^3.0.10
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3
  flutter_bloc: ^6.0.6
  flutter_launcher_icons: ^0.8.1
  flutter_local_notifications: ^3.0.1+4
  fluttertoast: ^3.1.3
  get: ^3.5.1
  google_fonts: ^1.1.1
  google_maps_flutter: ^0.5.21+15
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  provider: ^4.0.1
  pull_to_refresh: ^1.6.2
  shared_preferences: ^0.5.6
  skeleton_text: ^1.0.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/tower.png"

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/naruto.jpg
    - images/Said.jpg
    - images/tower.png
    - images/laptop.png
    - images/user.png
    - images/icon_edit.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
