name: flutter_monisite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3
  google_maps_flutter: ^0.5.21+15
  http: ^0.12.0+3
  firebase_core: ^0.4.3+1
  provider: ^4.0.1
  shared_preferences: ^0.5.6
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1
  charts_flutter: ^0.8.1
  google_fonts: ^0.3.2
  pull_to_refresh: ^1.5.7
  auto_route: ^0.2.1
  build_runner: ^1.7.3
  flutter_local_notifications: ^1.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.2.1+3


flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/naruto.jpg
    - images/Said.jpg
    - images/tower.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
