name: flutter_monisite
description: A new Flutter project.

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  package_info_plus: ^3.0.2
  provider: ^6.0.4
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  # Utils
  flutter_local_notifications: ^14.1.1


  # Firebase
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.9
  firebase_remote_config: ^3.0.9
  firebase_messaging: ^14.2.1
  firebase_auth: ^4.6.1
  firebase_performance: ^0.9.2+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/tower.png"

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/naruto.jpg
    - images/Said.jpg
    - images/tower.png
    - images/laptop.png
    - images/user.png
    - images/icon_edit.png
    - images/placeholder.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
