name: flutter_monisite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.2.1
  charts_flutter: ^0.8.1
  cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.4
  dio: ^3.0.10
  firebase_auth: ^0.15.3
  firebase_core: ^0.4.3+1
  firebase_messaging: ^6.0.9
  flutter_bloc: ^6.0.6
  flutter_local_notifications: ^1.1.6
  fluttertoast: ^3.1.3
  get: ^3.5.1
  google_fonts: ^1.1.1
  google_maps_flutter: ^0.5.21+15
  provider: ^4.0.1
  pull_to_refresh: ^1.5.7
  shared_preferences: ^0.5.6
  skeleton_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/naruto.jpg
    - images/Said.jpg
    - images/tower.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
